spring:
  profiles:
    active: local

# logging 설정
logging:
  level:
    root: INFO
    sql: trace
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS,Asia/Seoul} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS,Asia/Seoul} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  file:
    name: logs/dev_log.log
---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/angelhack?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useLegacyDatetimeCode=false
    username: teamrocket
    password: teamrocket
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
        lob:
        non_contextual_creation: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
---
spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rds-anglehack.cutixbfyzqqm.ap-northeast-2.rds.amazonaws.com:3306/anglehack?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useLegacyDatetimeCode=false
    username: teamrocket
    password: teamrocket
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
        lob:
        non_contextual_creation: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
---
cloud:
  aws:
    credentials:
      accessKey: 액세스
      secretKey: 시크릿 키
    s3:
      bucket: issue-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false